### Check API status (GET /)
GET http://localhost:5201/
Accept: application/json

### Bulk insert users (POST /cashKuber)
POST http://localhost:5201/cashKuber
Content-Type: application/json
api-key: moneyview

[
  {
    "Name": "vishu",
    "Phone": "9676543226",
    "Email": "vishu@example.com",
    "Employment": "IT ",
    "Pan": "SBFDF1234F",
    "Pincode": "110001",
    "Income": "50000",
    "City": "Hamirpur",
    "State": "HP",
    "Dob": "1990-01-01",
    "Gender": "Male",
    "PartnerId": "partner123"
  },
  {
    "Name": " Raman",
    "Phone": "9123456680",
    "Email": "raman@example.com",
    "Employment": "Nurse",
    "Pan": "NRRR5678X",
    "Pincode": "560001",
    "Income": "75000",
    "City": "Bangalore",
    "State": "Karnataka",
    "Dob": "1992-05-12",
    "Gender": "Female",
    "PartnerId": "partner123"
  }
]
